---
- name: Delete collection(s) API call
  uri:
    url: '{{ solr_cloud_restore_base_url }}/collections?'
    body: '{{ params | join ("&") }}'
    method: POST
  vars:
    params:
      - action=DELETE
      - 'name={{ item }}'
      - 'async={{ ansible_date_time.epoch }}-delete-{{ item }}'
  loop: '{{ delete_collections }}'
  register: delete_colection_call

- name: Check request ids for completed deletion of collection
  uri:
    url: '{{ solr_cloud_restore_base_url }}/collections?'
    body: '{{ params | join("&") }}'
    method: POST
  vars:
    params:
      - action=requeststatus
      - 'requestid={{ item }}'
    request_ids: '{{ delete_colection_call | json_query("results[].json.requestid") }}'
    state: '{{ delete_status | json_query("json.status.state") }}'
  loop: '{{ request_ids }}'
  register: delete_status
  until: state == 'completed'
  failed_when: state == 'failed'
  retries: '{{ solr_cloud_restore_retries }}'
  delay: '{{ solr_cloud_restore_delay }}'

#- name: Get index offset from delete tasks
#  set_fact:
#    index_offset: '{{ delete_colection_call | json_query("results[-1].ansible_loop.index") + index_offset | d (0) | int }}'