---
- name: List objects in s3
  aws_s3:
    bucket: '{{ item.bucket_name | d (sc_restore_bucket) }}'
    prefix: '{{ item.bucket_prefix | d (sc_restore_bucket_prefix) | d (omit) }}'
    mode: list
  loop: '{{ sc_restore_list }}'
  register: s3_objects

- name: Create new restore_list with associated object list
  set_fact:
    __sc_restore_list: '{{ __sc_restore_list | d([]) + [item.0 | combine({"s3_keys": item.1.s3_keys | d () })] }}'
  loop: '{{ sc_restore_list | zip(s3_objects.results) | list }}'

- name: Fail task if no backups are found
  fail:
    msg: 'No backup files were found at {{ item.bucket_prefix | d (sc_restore_bucket_prefix) }} for {{ item.restore_name }}!'
  loop: '{{ __sc_restore_list }}'
  when: item.s3_keys | length == 0

- debug:
    msg: '{{ item.s3_keys | map("regex_search", regexp) | first }}'
  loop: '{{ __sc_restore_list }}'
  vars:
    regexp: '{{ item.restore_epoch }}'
    select_query: '{{ item.restore_epoch }}'
- pause:


- debug:
    msg:  'No epoch matching was found!!'
  loop: '{{ __sc_restore_list }}'
  when: 
    - item.restore_epoch | lower != "latest"
    - item.restore_epoch is not search(item.s3_keys)


- name: Fail task if given epoch is not found
  fail:
    msg: 'No backup matching {{ item.restore_name }}-{{ item.restore_epoch }} was found!'
  loop: '{{ __sc_restore_list }}'
  when:
    - item.restore_epoch | lower != "latest"
    - item | selectattr("s3_keys", "contains", item.restore_epoch) | list | length == 0
  
- debug:
    var: __sc_restore_list

- pause:

- name: Get combined unique list of objects
  set_fact:
    combined_object_list: '{{ s3_objects | json_query("results[].s3_keys[]") | list | unique }}'

- name: Get latest object
  set_fact:
    latest_backup_list: '{{ combined_object_list | select("search", search_query) | d (False) | list }}'
  loop: '{{ sc_restore_list }}'
  when: item.restore_epoch | lower == 'latest' 
  vars:
    search_query: '*{{ item.restore_name }}*'

- debug:
    var: sc_restore_list | length

- pause:
