---
- name: List objects in s3
  aws_s3:
    bucket: '{{ item.bucket_name | d (sc_restore_bucket) }}'
    prefix: '{{ item.bucket_prefix | d (sc_restore_bucket_prefix) | d (omit) }}'
    mode: list
  loop: '{{ sc_restore_list }}'
  register: s3_objects

- name: Show s3 objects
  debug:
    var: s3_objects

- set_fact:
    combined_object_list: '{{ s3_objects | json_query("results[].s3_keys[]") | list | unique }}'

- debug:
    var: '{{ item | length }}'
  loop:
    - '{{ s3_objects["results"][0]["s3_keys"] }}'
    - '{{ combined_object_list }}'
- pause:
