---
# tasks file for emorylib_solr_cloud_restore_from_s3
#- name: Include tasks for getting directory key from local path
#  include_tasks:
#    file: get-directory-key.yml

#- name: Include tasks for downloading folder from s3
#  include_tasks:
#    file: download-from-s3.yml

- name: Include tasks to check for matching collections
  include_tasks:
    file: check-for-matching-collection.yml

- name: Include tasks deleting collection that will be recreated
  include_tasks:
    file: delete-collections.yml
    vars:
      index: '{{ index | d (0) + index_offset | d (0) }}'
      delete_collections: '{{ check_if_collection_already_exists | list }}'
  when: check_if_collection_already_exists != "none"

- name: Include tasks for restoring collection
  include_tasks:
    file: restore-collection.yml
    apply:
      tags: restore-collection
  tags: restore-collection